export const columns = [
  { name: "ID", uid: "#" },
  { name: "NAME", uid: "name" },
  { name: "ROLE", uid: "role" },
  { name: "TEAM", uid: "team" },
  { name: "STATUS", uid: "status" },
  { name: "ACTIONS", uid: "actions" },
];
export const users = [
  {
    id: 1,
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
  },
  {
    id: 2,
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    name: "Zoey Lang",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
  },
  {
    id: 3,
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    name: "Jane Fisher",
    role: "Senior Developer",
    team: "Development",
    status: "active",
  },
  {
    id: 4,
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    name: "William Howard",
    role: "Community Manager",
    team: "Marketing",
    status: "vacation",
  },
  {
    id: 5,
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    name: "Kristen Copper",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
  },
  {
    id: 6,
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
  },
  {
    id: 10,
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    name: "Kristen Copper",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
  },
  {
    id: 8,
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    name: "Jane Fisher",
    role: "Senior Developer",
    team: "Development",
    status: "active",
  },
  {
    id: 7,
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    name: "Zoey Lang",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
  },

  {
    id: 9,
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    name: "William Howard",
    role: "Community Manager",
    team: "Marketing",
    status: "vacation",
  },
  {
    id: 11,
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
  },
  {
    id: 12,
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    name: "Kristen Copper",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
  },
  {
    id: 13,
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    name: "Jane Fisher",
    role: "Senior Developer",
    team: "Development",
    status: "active",
  },
  {
    id: 14,
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    name: "Zoey Lang",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
  },
  {
    id: 15,
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
  },
  {
    id: 16,
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    name: "Kristen Copper",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
  },
];
